buildVariable: true
familyName: Noto Sans Armenian
googleFonts: true
includeSubsets:
- from: Noto Sans
  name: GF_Latin_Core
- from: Noto Sans
  ranges:
  - end: 8228
    start: 8228
recipeProvider: noto
sources:
- NotoSansArmenian.glyphspackage
